steps:

# Docker Image Creation
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT:$COMMIT_SHA'
      - .

# Deploying image in Google Cloud
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT:$COMMIT_SHA'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |-
        gcloud run deploy $_CLOUD_RUN_PROJECT \
        --image=gcr.io/$PROJECT_ID/$_CLOUD_RUN_PROJECT:$COMMIT_SHA \
        --region=us-east4 --platform=managed \
        --set-env-vars GCP_FIRESTORE_COLLECTION_CUSTOMERS=${_GCP_FIRESTORE_COLLECTION_CUSTOMERS},GCP_FIRESTORE_COLLECTION_ISSUES=${_GCP_FIRESTORE_COLLECTION_ISSUES},GCP_FIRESTORE_COLLECTION_COUNTER_LOGS=${_GCP_FIRESTORE_COLLECTION_COUNTER_LOGS},GCP_FIRESTORE_COLLECTION_REQUESTS=${_GCP_FIRESTORE_COLLECTION_REQUESTS},GCP_FIRESTORE_COLLECTION_USERS=${_GCP_FIRESTORE_COLLECTION_USERS},JWT_SECRET_KEY=${_JWT_SECRET_KEY},JWT_TOKEN_DURATION_MS=${_JWT_TOKEN_DURATION_MS},NODE_ENV=${_NODE_ENV},GCP_FIRESTORE_PROJECT_ID=${PROJECT_ID},BUSINESS_SERVICE_PRICE=${_BUSINESS_SERVICE_PRICE},BUSINESS_SERVICE_PRICE_UNIT=${_BUSINESS_SERVICE_PRICE_UNIT},GCP_FIRESTORE_COLLECTION_INVOICES=${_GCP_FIRESTORE_COLLECTION_INVOICES}
    entrypoint: bash


substitutions:
  _GCP_FIRESTORE_COLLECTION_CUSTOMERS: customers
  _GCP_FIRESTORE_COLLECTION_ISSUES: issues
  _GCP_FIRESTORE_COLLECTION_COUNTER_LOGS: counter-logs
  _GCP_FIRESTORE_COLLECTION_REQUESTS: requests
  _GCP_FIRESTORE_COLLECTION_USERS: users
  _GCP_FIRESTORE_COLLECTION_INVOICES: invoices
  _JWT_SECRET_KEY: 
  _JWT_TOKEN_DURATION_MS: '3600'
  _CLOUD_RUN_PROJECT: acasapufe-backend
  _NODE_ENV: development
  _BUSINESS_SERVICE_PRICE: '8.25'
  _BUSINESS_SERVICE_PRICE_UNIT: '15',